-- Son consultas para consultar varias tablas en una sola sentencia
#Mostrar las entradas con el nombre del autor y el nombre de la categoria
SELECT E.ID,
    E.TITULO,
    U.NOMBRE AS 'AUTOR',
    C.NOMBRE AS 'CATEGORIA'
FROM ENTRADAS E,
    USUARIOS U,
    CATEGORIAS C
WHERE E.USUARIO_ID = U.ID
    AND E.CATEGORIA_ID = C.ID;
#INNER JOIN#
SELECT E.ID,
    E.TITULO,
    U.NOMBRE,
    C.NOMBRE AS 'CATEGORIA'
FROM ENTRADAS E
    INNER JOIN USUARIOS U ON E.USUARIO_ID = U.ID
    INNER JOIN CATEGORIAS C ON E.CATEGORIA_ID = C.ID;
#Mostrar el nombre de las categorias y al lado cuantas entradas tienen
SELECT C.NOMBRE,
    COUNT(E.ID) AS 'ENTRADAS'
FROM CATEGORIAS C,
    ENTRADAS E
WHERE E.CATEGORIA_ID = C.ID
GROUP BY E.CATEGORIA_ID;
#LEFT JOIN
SELECT C.NOMBRE,
    COUNT(E.ID) AS 'ENTRADAS'
FROM CATEGORIAS C
    LEFT JOIN ENTRADAS E ON C.ID = E.CATEGORIA_ID
GROUP BY C.ID;
#RIGHT JOIN#
SELECT C.NOMBRE,
    COUNT(E.ID) AS 'ENTRADAS'
FROM ENTRADAS E
    RIGHT JOIN CATEGORIAS C ON C.ID = E.CATEGORIA_ID
GROUP BY C.ID;
#Mostrar el email de los usuarios y al lado cuantas entradas tienen
SELECT U.EMAIL,
    COUNT(E.ID)
FROM USUARIOS U,
    ENTRADAS E
WHERE U.ID = E.USUARIO_ID
GROUP BY E.USUARIO_ID;
#-----INNER JOIN-------#
SELECT U.EMAIL,
    COUNT(E.ID)
FROM USUARIOS U
    INNER JOIN ENTRADAS E ON U.ID = E.USUARIO_ID
GROUP BY U.ID;